#!/bin/sh

# Initialize X resource database (if ~/.Xresources is present).
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Executed by startx (run your window manager from here).
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Keyboard layout.
setxkbmap br -variant abnt2

# Autostart programs:
xwallpaper --stretch Imagens/dwm.png    # Wallpaper.
dunst &                                 # Notification daemon.
xcompmgr &                              # Compositor.
lxpolkit &                              # Polkit.
slstatus &                              # Status bar.
clipmenud &                             # Clipboard manager.
xautolock -time 10 -locker slock &      # Lock screen when inactive for 10 minutes.
exec dwm > ~/.dwm.log
