#!/bin/sh

# Initialize X resource database (if ~/.Xresources is present).
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# Executed by startx (run your window manager from here).
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set keyboard layout.
setxkbmap br -variant abnt2

# Set wallpaper.
nitrogen --restore &

# Look screen after 10min of inactivity with slock.
xautolock -time 10 -locker slock &

# Autostart programs.
autostart="xcompmgr dunst lxpolkit slstatus clipmenud"

for program in $autostart; do
    pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Loop and execute DWM.
while true; do
    dwm >/dev/null 2>&1
done

exec dwm
